#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import shutil
import argparse
import subprocess

def change_extension(filename, newextension) -> str:
    return newextension.join(filename.rsplit('.')[:-1]+[""])

parser = argparse.ArgumentParser()
parser.add_argument("-c", "--clean", help="remove all files generated by this script", action="store_true")

if parser.parse_args().clean:
    shutil.rmtree("out", True)
    sys.exit()

compileFiles = []
linkerFiles = []

for file in os.listdir("src"):
    if file.endswith(".cpp"):
        cppFile = os.path.join("src", file)
        objFile = os.path.join("out", change_extension(file, '.o'))

        compileFiles.append((cppFile, objFile))
        linkerFiles.append(objFile)

os.makedirs("out", exist_ok=True)
# create objects
for cpp, obj in compileFiles:
    print(subprocess.getoutput(f"g++ -c {cpp} -o {obj}"))

# linker
files = " ".join(linkerFiles)
print(subprocess.getoutput(f"g++ {files} -o out/main"))


